# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

jobs:
- job: Linux
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      lnx32:
        platform.type : 'lnx32'
      lnx32e:
        platform.type : 'lnx32e'
    maxParallel: 2
  steps:
  - script: sudo apt-get update && sudo apt-get install gcc-multilib g++-multilib openjdk-8-jdk git
    displayName: 'apt-get'
  - script: |
      scripts/mklfpk.sh ${$(platform.type):3}
      scripts/tbb.sh ${$(platform.type):3}
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      export CPATH=$JAVA_HOME/include:$JAVA_HOME/include/linux:$CPATH 
      make daal -j4 PLAT=$(platform.type) COMPILER=gnu REQCPU="avx2"
    displayName: 'make'
  - script: |
      cp -R __release_lnx_gnu $(Build.ArtifactStagingDirectory)/
    displayName: 'Copy build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: '$(platform.type) build'
      targetPath: '__release_lnx_gnu'
# conformance
  - script: |
      which git
      git --version
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      source activate base
      conda-env list
      conda activate base
      conda list
      conda create -y -n conformance python=3.7
      conda activate conformance
      conda install -y -c conda-forge mpich tbb-devel cython jinja2 numpy clang-tools
      export TBBROOT=$CONDA_PREFIX
      export MPIROOT=$CONDA_PREFIX
      source __release_lnx_gnu/daal/bin/daalvars.sh intel64
      git clone https://github.com/IntelPython/daal4py
      conda-env list
      conda list
      echo ACTIVATE_CONFORMANCE_ENVIROMENT
      conda activate conformance
      conda list
      echo
      echo
      echo
      echo DAALROOT
      echo $DAALROOT
      echo
      echo TBBROOT
      echo $TBBROOT
      echo
      echo MPIROOT
      echo $MPIROOT
      echo
      echo CPATH
      echo $CPATH
      echo
      echo LD_LIBRARY_PATH
      echo $LD_LIBRARY_PATH
      echo
      echo START
      echo
      pwd
      cd daal4py
      pwd
      python setup.py develop
      cd ..
      pwd
      echo
      conda activate conformance
      conda install -y -c intel scikit-learn
      conda install -y -c conda-forge pytest
      conda activate conformance
      pwd
      cd .ci/conformance/
      pwd
      python run_tests.py
      cd ../../
      pwd
    timeoutInMinutes: 15
    displayName: 'Create Anaconda environment'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'conformance tests report'
      targetPath: '.ci/conformance/report.html'
- job: macOS
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      mac32e:
        platform.type : 'mac32e'
  steps:
  - script: |
      scripts/mklfpk.sh ${$(platform.type):3}
      scripts/tbb.sh ${$(platform.type):3}
      export JAVA_HOME=$(/usr/libexec/java_home -v 12)
      export PATH=$JAVA_HOME/bin:$PATH
      export CPATH=$JAVA_HOME/include:$JAVA_HOME/include/darwin:$CPATH
      make daal -j4 PLAT=$(platform.type) COMPILER=clang REQCPU="avx2"
    displayName: 'make'
  - script: |
      cp -R __release_mac_clang $(Build.ArtifactStagingDirectory)/
    displayName: 'Copy build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Mac build'
      targetPath: '__release_mac_clang'
# Windows build is temporary disabled
#- job: Windows
#  pool:
#    vmImage: 'vs2017-win2016'
#  steps:
#  - script: |
#      java -version
#      set INCLUDE=%JAVA_HOME%\include;%JAVA_HOME%\include\win32;%INCLUDE%
#      call .\scripts\mklfpk.bat && call .\scripts\tbb.bat
#      call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall" x64
#      call .\externals\tbb\bin\tbbvars.bat intel64 14_uwp
#     make daal COMPILER=vc REQCPU="avx2" PLAT="win32e"


