# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

jobs:
- job: 'ClangFormat'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - script: |
        .ci/env/clang.sh
      displayName: 'apt-get'
    - script: |
        .ci/scripts/clang-format.sh
      displayName: 'clang-format check'
      failOnStderr: true
- job: Linux
  timeoutInMinutes: 0
  variables:
    release.dir: '__release_lnx_gnu'
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      lnx32:
        platform.type : 'lnx32'
      lnx32e:
        platform.type : 'lnx32e'
    maxParallel: 2
  steps:
  - script: sudo apt-get update && sudo apt-get install gcc-multilib g++-multilib openjdk-8-jdk
    displayName: 'apt-get'
  - script: |
      .ci/scripts/build.sh --platform $(platform.type)
    displayName: 'make'
  - script: |
      cp -R $(release.dir) $(Build.ArtifactStagingDirectory)/
    displayName: 'Copy build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: '$(platform.type) build'
      targetPath: '$(release.dir)'
  - script: |
      .ci/scripts/test.sh --test-kind examples --build-dir $(release.dir) --platform $(platform.type)
    displayName: 'examples'
  - script: |
      .ci/scripts/conformance_test.sh --build-dir $(release.dir) --arch $(platform.type)
    timeoutInMinutes: 15
    displayName: 'conformance tests'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'conformance tests report $(platform.type)'
      targetPath: '.ci/scripts/conformance-scripts/report.html'
- job: macOS
  timeoutInMinutes: 0
  variables:
    release.dir: '__release_mac_clang'
  pool: 
    vmImage:  'macOS-10.15'
  strategy:
    matrix:
      mac32e:
        platform.type : 'mac32e'
  steps:
  - script: |
      .ci/scripts/build.sh --platform $(platform.type)
    displayName: 'make'
  - script: |
      cp -R $(release.dir) $(Build.ArtifactStagingDirectory)/
    displayName: 'Copy build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Mac build'
      targetPath: '$(release.dir)'

# Windows build is temporary disabled
#- job: Windows
#  pool:
#    vmImage: 'vs2017-win2016'
#  steps:
#  - script: |
#      java -version
#      set INCLUDE=%JAVA_HOME%\include;%JAVA_HOME%\include\win32;%INCLUDE%
#      call .\scripts\mklfpk.bat && call .\scripts\tbb.bat
#      call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall" x64
#      call .\externals\tbb\bin\tbbvars.bat intel64 14_uwp
#     make daal COMPILER=vc PLAT="win32e"


