trigger:
  branches:
    include:
    - master
    - releases
    - rls/*
  paths:
    include:
    - include
    - docs
    - examples

pr:
  branches:
    include:
    - master
    - releases
    - rls/*
  paths:
    include:
    - include
    - docs
    - examples

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: |
    cd docs 
    sudo apt-get install python3-setuptools
    sudo pip3 install -r requirements.txt
  displayName: 'Install requirements'

- script: |
    cd docs 
    make html
  displayName: 'Build documentation'
  name: build_documentation

- script: |
    cp -R docs/build $(Build.ArtifactStagingDirectory)/html
  displayName: 'Copy build'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'onedal-documentation'
    targetPath: '$(Build.ArtifactStagingDirectory)/html'

- script: |
    cp docs/docbuild-log.txt $(Build.ArtifactStagingDirectory)/
  displayName: "Copy docbuild log file"
  dependsOn: build_documentation
  condition: failed()

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'docbuild-log'
    targetPath: '$(Build.ArtifactStagingDirectory)/docbuild-log.txt'
