trigger:
  branches:
    include:
    - master
    - releases
    - rls/*
  paths:
    include:
    - include
    - docs
    - examples

pr:
  branches:
    include:
    - master
    - releases
    - rls/*
  paths:
    include:
    - include
    - docs
    - examples

pool:
  vmImage: 'ubuntu-latest'
  
jobs:

- job: build_doc

  steps:
  - script: |
      cd docs 
      sudo apt-get install python3-setuptools
      sudo pip3 install -r requirements.txt
    displayName: 'Installing requirements'

  - script: |
      cd docs 
      make html
    displayName: 'Building documentation'

  - script: |
      cp -R docs/build $(Build.ArtifactStagingDirectory)/html
    displayName: 'Copy build'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'onedal-documentation'
      targetPath: '$(Build.ArtifactStagingDirectory)/html'

- job: create_docbuild_log
  dependsOn: build_doc
  condition: failed()

  steps:

  - script: |
      cp docs/docbuild-log.txt $(Build.ArtifactStagingDirectory)/
    displayName: "Copy docbuild log file"

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'docbuild-log'
      targetPath: '$(Build.ArtifactStagingDirectory)/docbuild-log.txt'
