trigger:
  branches:
    include:
    - master
    - releases
    - rls/*
  paths:
    include:
    - include
    - docs

pr:
  branches:
    include:
    - master
    - releases
    - rls/*
  paths:
    include:
    - include
    - docs

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd daal/docs 
    pip install -r requirements.txt
  displayName: 'Installing requerements'

- script: |
    cd daal/docs 
    make html
  displayName: 'Building documentation'

- script: |
    cp -R build/html $(Build.ArtifactStagingDirectory)/
  displayName: 'Copy build'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'Docs build'
    targetPath: 'html'